### PR TITLE
Fix missing Error check in e2e test

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve? 
Fix missing Error check in e2e test

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by yeya24** [comment]
@Yisaer Does this fix the flaky? Seems this is another thing.

**Comment by Yisaer** [comment]
> @Yisaer Does this fix the flaky? Seems this is another thing.

I'm not sure. In the existed log the error happened in verify recovering the chaos, but it may still be caused by the applying the chaos that we forgot to verify applying chaos error here. I think this request would expose the root error about the flaky e2e test.

To solve the flaky test, we need to get the logs of chaos controller which I am working on it.

**Comment by yeya24** [comment]
Please fix CI and then we can merge. Anyway this change LGTM

**Pull request merged**
