### PR TITLE
document: update link

### PR DESCRIPTION
**Pull request by tsunokawa**
### What problem does this PR solve? 

Update a link to the [Run Chaos Mesh] document.

### What is changed and how does it work?

A document

### Check List 

Tests 

 - No code

Code changes

 - No code

Side effects

 - No code

Related changes

 - No code

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
@tsunokawa thank you for your contribution. please sign CLA

**Comment by cwen0** [comment]
@tsunokawa Thanks for your contribution. Please, sign CLA first.

**Comment by tsunokawa** [comment]
@zhouqiang-cl I signed the CLA. Please check again.

**Comment by zhouqiang-cl** [comment]
@tsunokawa Could you provide your twitter name? thank you

**Comment by tsunokawa** [comment]
@zhouqiang-cl My Twitter name is @tsunokawa. Thank you.

**Pull request merged**
