### PR TITLE
refine pprof server with builder template

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve? 

Refine pprof http server to avoid warning by revive brought by #251 .

Should we add revive warning detection in CI?

### CODE REVIEW

**Comment by cwen0** [comment]
@YangKeao Fix CI, please.

**Comment by YangKeao** [comment]
It seems that `time-chaos`'s test is quite unstable :cry:

**Comment by zhouqiang-cl** [comment]
@yeya24 could you help to review too?

**Pull request merged**
