### PR TITLE
add grace period for pod kill chaos

### PR DESCRIPTION
**Pull request by namco1992**
### What problem does this PR solve?

Solve #569.

### What is changed and how does it work?
Added a `gracePeriod` field in the `PodChaos` CRD.

### Check List

Tests

- Unit test
- E2E test
- Manual test (add detailed scripts or steps below)

Code changes

- Has Go code change

Related changes

- Need to update the documentation to add `gracePeriod` field.

### Does this PR introduce a user-facing change?

```release-note
The gracePeriod field is available in podChaos to set the duration before the pod is deleted.
```

### CODE REVIEW

**Comment by cwen0** [comment]
@namco1992 Thanks for your contribution! Can you fix [`DCO`](https://github.com/pingcap/chaos-mesh/pull/663/checks?check_run_id=819143616) checker?

**Comment by namco1992** [comment]
@cwen0 Fixed, thanks!

**Pull request merged**
