### PR TITLE
Store experiment when it was created

### LINKED ISSUE #657: Fail to archive experiment
## Bug Report

When to archive the experiment, we found that the experiment may be deleted by `chaos-operator`, so this action will cause the archive action to fail.

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?

Fix #657 #557 

### What is changed and how does it work?

* store experiment when it was created 
* add `archived` field to archive_eperiment struct, when some experiment was deleted and update `archived` to `true`

### CODE REVIEW

**Comment by yeya24** [comment]
TBH I don't think it is a good choice. The experiment object can be updated/changed after it is created. Then do we want to update the archive experiment in db every time?

**Comment by cwen0** [comment]
> TBH I don't think it is a good choice. The experiment object can be updated/changed after it is created. Then do we want to update the archive experiment in db every time?

Yes, I think we can update it in DB every time.

**Comment by cwen0** [comment]
@YangKeao @yeya24 PTAL, thanks!

**Pull request merged**
