### PR TITLE
Record chaos event to dbstore

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?  

#482 

### What is changed and how does it work? 

In this pr, we will watch all chaos object and record chaos events to DB store.

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
> Is the information currently stored sufficient for API use? Should pod-related information be added to the event? There is an interface to get the event on the specified pod, that is to say we want to get the event by pod name and pod NS, so should we add pod information to the event?

Updated

**Comment by cwen0** [comment]
@yeya24 If we delete this chaos, the `Experiment.Phase` will be set to `ExperimentPhaseFinishedCWen` at here https://github.com/pingcap/chaos-mesh/blob/master/controllers/common/types.go#L78, So the `finish_time` won't be empty. In addition, we will delete all incomplete events when to start chaos-server.

**Comment by yeya24** [comment]
I will merge it when CI passes if you think it is okay. @cwen0 @fewdan

**Pull request merged**
