### PR TITLE
Add hostNetwork in chaos-daemon-daemonset.yaml

### PR DESCRIPTION
**Pull request by tsthght**
### What problem does this PR solve?
HostPort services do not work in some k8s environment. In our environment, the error is reported as follows: 

```
2020-06-18T02:49:15.160Z ERROR controllers.TimeChaos failed to apply chaos on all pods {"reconciler": "timechaos", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp xx.xx.xx.xx:2223: connect: connection refused\""}
```
ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#hostport-services-do-not-work

### What is changed and how does it work?

Add hostNetwork in chaos-daemon-daemonset.yaml

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by cwen0** [comment]
@tsthght Thanks for your contribution!

**Comment by Yisaer** [comment]
I think the `hostNetwork` could be an option for daemon?

**Comment by Gallardot** [comment]
> I think the `hostNetwork` could be an option for daemon?

agree

**Comment by tsthght** [comment]
> I think the `hostNetwork` could be an option for daemon?

Should this PR  be closed or be changed to the following form?

```
{{- if .Values.DefineHostNetwork }}
hostNetwork: true
{{- end }}
```

PTAL @Yisaer @Gallardot @cwen0

**Comment by yeya24** [comment]
> > I think the `hostNetwork` could be an option for daemon?
> 
> Should this PR be closed or be changed to the following form?
> 
> ```
> {{- if .Values.DefineHostNetwork }}
> hostNetwork: true
> {{- end }}
> ```
> 
> PTAL @Yisaer @Gallardot @cwen0



> > I think the `hostNetwork` could be an option for daemon?
> 
> Should this PR be closed or be changed to the following form?
> 
> ```
> {{- if .Values.DefineHostNetwork }}
> hostNetwork: true
> {{- end }}
> ```
> 
> PTAL @Yisaer @Gallardot @cwen0

I prefer `.Values.chaosDaemon.hostNetwork`. Note that we also need `.Values.bpfki.hostNetwork` as well.

**Comment by Gallardot** [comment]
> I prefer `.Values.chaosDaemon.hostNetwork`. Note that we also need `.Values.bpfki.hostNetwork` as well.

Agree. After that we also need to update helm's `README.md` and `values.yaml`.  @tsthght

**Comment by tsthght** [comment]
> > I prefer `.Values.chaosDaemon.hostNetwork`. Note that we also need `.Values.bpfki.hostNetwork` as well.
> 
> Agree. After that we also need to update helm's `README.md` and `values.yaml`. @tsthght

Thanks, we will modify it.

**Comment by tsthght** [comment]
I had modified it, PTAL @yeya24 @Gallardot @cwen0

**Comment by cwen0** [comment]
@tsthght Can you help us to add this variable in the [README.md](https://github.com/pingcap/chaos-mesh/blob/master/helm/chaos-mesh/README.md#configuration)?  In addition, please sign CLA. Thanks!

**Comment by tsthght** [comment]
> @tsthght Can you help us to add this variable in the [README.md](https://github.com/pingcap/chaos-mesh/blob/master/helm/chaos-mesh/README.md#configuration)? In addition, please sign CLA. Thanks!

Thanks , I will do that.

**Pull request merged**
