### PR TITLE
Add boilerplate check

### LINKED ISSUE #550: Support licence check in CI
## Feature Request

**Is your feature request related to a problem? Please describe:**

Automatically check boiler template in CI. An example is https://github.com/pingcap/tidb-operator/blob/c09f6189840917e6e8c9b7c3e75cccd41ef28b5d/hack/verify-boilerplate.sh

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What problem does this PR solve? 

Fixes #550

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
Seems CI broken

**Comment by yeya24** [comment]
@zhouqiang-cl @cwen0 Please review. CI is green :)

**Comment by cwen0** [comment]
@yeya24 Please fix conflicts! Thanks!

**Pull request merged**
