### PR TITLE
Support reorder in network delay chaos

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What is changed and how does it work?

Add a reorder fields in network delay chaos

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
@yeya24 please fix ci

**Comment by YangKeao** [comment]
I think reorder has to cooperate with delay, doesn't it?

```
to use reordering, a delay option must be specified. There are two
ways to use this option (assuming 'delay 10ms' in the options list).
```

**Comment by yeya24** [comment]
@YangKeao Thanks for it! Sorry I miss that. What about make reorder an option field in delay?

**Comment by zhouqiang-cl** [comment]
> @YangKeao Thanks for it! Sorry I miss that. What about make reorder an option field in delay?

I think we can. @YangKeao PTAL

**Comment by YangKeao** [comment]
@yeya24 Great. But notice that `nullable` is not supported in lower version of kubernetes, so we can only use `optional` + emitempty to add reorder related field.

**Comment by yeya24** [comment]
> /test

I haven't updated this PR as @YangKeao said, let me make the state to WIP.

**Comment by yeya24** [comment]
Ready for review now. But I found the netem reorder is not that easy to test.

**Pull request merged**
