### PR TITLE
Build dashboard-server-frontend in docker

### PR DESCRIPTION
**Pull request by Gallardot**
### What problem does this PR solve? 
#376 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@Gallardot Does the Makefile need to be updated?

**Comment by Gallardot** [comment]
> @Gallardot Does the Makefile need to be updated?

@cwen0 I think it depends on CI/CD.

Our CI/CD pipeline just 
```
make image
make docker-push
```
It works fine.

But If your CI/CD pipeline includes `make dashboard-server-frontend`. It will build the dashboard-server-frontend twice.

**Comment by cwen0** [comment]
> > @Gallardot Does the Makefile need to be updated?
> 
> @cwen0 I think it depends on CI/CD.
> 
> Our CI/CD pipeline just
> 
> ```
> make image
> make docker-push
> ```
> 
> It works fine.
> 
> But If your CI/CD pipeline includes `make dashboard-server-frontend`. It will build the dashboard-server-frontend twice.

Got it.

**Pull request merged**
