### PR TITLE
Add unit test (webhook/config/config_test.go)

### PR DESCRIPTION
**Pull request by fewdan**
### What problem does this PR solve?
Add unit test (webhook/config/config_test.go)

### Check List

Tests 

 - Unit test

Code changes

 - Has Go code change

Side effects

 - NO

Related changes

 - NO

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
please resolve conflict @fewdan

**Comment by cwen0** [comment]
@lucklove PTAL

**Pull request merged**
